spring.application.name=foodiesapi
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGO_URI}
jwt.secret.key=${JWT_SECRET}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true

# Gmail SMTP Configuration
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587

# Brevo SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true

# AWS S3 Configuration
aws.s3.bucketname=${AWS_S3_BUCKETNAME:}
aws.region=${AWS_REGION:}
aws.access.key=${AWS_ACCESS_KEY:}
aws.secret.key=${AWS_SECRET_KEY:}

# Razorpay Configuration
razorpay_key=${RAZORPAY_KEY:}
razorpay_secret=${RAZORPAY_SECRET:}

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

